# Generated by Django 6.0.2 on 2026-09-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Director'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='director', max_length=20),
        ),
    ]
