[project]
name = "baxter"
version = "0.1.0"
description = "Efficient scrabble tournament manager"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dataclasses-json>=0.6.7",
    "django>=6.0.2",
    "python-decouple>=3.8",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=6.2.0",
    "ipython>=9.10.0",
    "pandas>=3.0.0",
]
