# Generated by Django 6.0.2 on 2026-02-06 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrants",
                        to="tournaments.division",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="tournaments.player",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("division", "number")},
            },
        ),
    ]
