# Generated by Django 6.0.2 on 2026-02-06 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_entrant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultSlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.IntegerField()),
                ("winner_score", models.IntegerField()),
                ("loser_score", models.IntegerField()),
                ("winner_started", models.BooleanField()),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_slips",
                        to="tournaments.division",
                    ),
                ),
                (
                    "loser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="losses",
                        to="tournaments.entrant",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wins",
                        to="tournaments.entrant",
                    ),
                ),
            ],
            options={
                "ordering": ["round"],
            },
        ),
    ]
