# Generated by Django 6.0.2 on 2026-02-09 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0005_resultslip"),
    ]

    operations = [
        migrations.CreateModel(
            name="DivisionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_pairings", models.JSONField(default=list)),
                (
                    "division",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tournaments.division",
                    ),
                ),
            ],
        ),
    ]
