# Generated by Django 6.0.2 on 2026-02-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0006_divisionsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultslip",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
