# Generated by Django 6.0.2 on 2026-02-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_resultslip_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entrant',
            unique_together={('division', 'number'), ('division', 'player')},
        ),
    ]
