# Generated by Django 6.0.2 on 2026-02-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0008_alter_entrant_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="is_test",
            field=models.BooleanField(default=False),
        ),
    ]
