# Generated by Django 6.0.2 on 2026-02-22 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0009_division_is_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pairing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.IntegerField()),
                ("repeats", models.IntegerField(default=0)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings",
                        to="tournaments.division",
                    ),
                ),
                (
                    "first",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings_as_first",
                        to="tournaments.entrant",
                    ),
                ),
                (
                    "second",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings_as_second",
                        to="tournaments.entrant",
                    ),
                ),
            ],
            options={
                "ordering": ["round"],
            },
        ),
    ]
