# Generated by Django 6.0.2 on 2026-02-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0010_add_pairing_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="division",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
