# Generated by Django 6.0.2 on 2026-02-25 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0011_division_soft_delete"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedPairing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_pairings",
                        to="tournaments.division",
                    ),
                ),
                (
                    "entrant1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_pairings_as_first",
                        to="tournaments.entrant",
                    ),
                ),
                (
                    "entrant2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_pairings_as_second",
                        to="tournaments.entrant",
                    ),
                ),
            ],
            options={
                "ordering": ["round_number"],
            },
        ),
    ]
