# Generated by Django 6.0.2 on 2026-03-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0012_fixedpairing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pairing",
            options={"ordering": ["round", "table"]},
        ),
        migrations.AddField(
            model_name="pairing",
            name="table",
            field=models.IntegerField(default=0),
        ),
    ]
