# Generated by Django 6.0.2 on 2026-03-14 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0013_add_table_to_pairing"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("table_number", models.IntegerField()),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_tables",
                        to="tournaments.division",
                    ),
                ),
                (
                    "entrant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_tables",
                        to="tournaments.entrant",
                    ),
                ),
            ],
            options={
                "ordering": ["round_number", "table_number"],
            },
        ),
    ]
