# Generated by Django 6.0.2 on 2026-04-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0014_add_fixed_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="published_through_round",
            field=models.IntegerField(default=0),
        ),
    ]
