# Generated by Django 6.0.2 on 2026-04-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0015_division_published_through_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="pairings_changed",
            field=models.BooleanField(default=False),
        ),
    ]
