# Generated by Django 6.0.2 on 2026-04-03 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0016_division_pairings_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultslip",
            name="pairing",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="result",
                to="tournaments.pairing",
            ),
        ),
        migrations.CreateModel(
            name="RoundPairings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("in_progress", "In Progress"),
                            ("finished", "Finished"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_pairings_set",
                        to="tournaments.division",
                    ),
                ),
            ],
            options={
                "ordering": ["round"],
                "unique_together": {("division", "round")},
            },
        ),
        migrations.AddField(
            model_name="pairing",
            name="round_pairings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pairings",
                to="tournaments.roundpairings",
            ),
        ),
    ]
