# Generated by Django 6.0.2 on 2026-04-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0017_resultslip_pairing_roundpairings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="division",
            name="pairings_changed",
        ),
        migrations.RemoveField(
            model_name="division",
            name="published_through_round",
        ),
    ]
