# Generated by Django 6.0.2 on 2026-05-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0018_remove_division_pairings_changed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="divisionsettings",
            name="board_table_map",
            field=models.JSONField(default=list),
        ),
    ]
