# Generated by Django 6.0.2 on 2026-06-01 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0019_divisionsettings_board_table_map"),
    ]

    operations = [
        migrations.CreateModel(
            name="DivisionEditVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=50)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_versions",
                        to="tournaments.division",
                    ),
                ),
            ],
            options={
                "unique_together": {("division", "scope")},
            },
        ),
    ]
