# Generated by Django 6.0.2 on 2026-06-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0021_divisioneditpresence"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="divisioneditversion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="divisioneditversion",
            name="division",
        ),
        migrations.DeleteModel(
            name="DivisionEditPresence",
        ),
        migrations.DeleteModel(
            name="DivisionEditVersion",
        ),
    ]
