# Generated by Django 6.0.2 on 2026-06-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0022_alter_divisioneditversion_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="divisionsettings",
            name="pairing_blocks",
            field=models.JSONField(default=list),
        ),
    ]
