# Generated by Django 6.0.2 on 2026-06-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0023_divisionsettings_pairing_blocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_provisional",
            field=models.BooleanField(default=False),
        ),
    ]
