# Generated by Django 6.0.2 on 2026-06-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_player_is_provisional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
