# Generated by Django 6.0.2 on 2026-06-23 07:02

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0025_tournament_is_fake'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrant',
            options={'base_manager_name': 'all_objects', 'ordering': ['number']},
        ),
        migrations.AlterModelManagers(
            name='entrant',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='is_bye',
            field=models.BooleanField(default=False),
        ),
    ]
