# Generated by Django 6.0.2 on 2026-07-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0029_roundpairings_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrant',
            name='dropped',
            field=models.BooleanField(default=False),
        ),
    ]
