# Generated by Django 6.0.2 on 2026-07-15 00:25

import tournaments.models
from django.db import migrations, models


def randomize_existing_seeds(apps, schema_editor):
    # AddField applies one computed default to every existing row, so give each
    # existing DivisionSettings its own seed.
    DivisionSettings = apps.get_model("tournaments", "DivisionSettings")
    for pk in DivisionSettings.objects.values_list("pk", flat=True):
        DivisionSettings.objects.filter(pk=pk).update(
            pairing_seed=tournaments.models.random_pairing_seed()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0030_entrant_dropped'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionsettings',
            name='pairing_seed',
            field=models.BigIntegerField(default=tournaments.models.random_pairing_seed),
        ),
        migrations.RunPython(
            randomize_existing_seeds, migrations.RunPython.noop
        ),
    ]
