# Generated by Django 6.0.2 on 2026-07-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0032_tournamentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionsettings',
            name='cop_config',
            field=models.JSONField(default=dict),
        ),
    ]
