# Generated by Django 6.0.2 on 2026-07-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0033_divisionsettings_cop_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionsettings',
            name='swiss_config',
            field=models.JSONField(default=dict),
        ),
    ]
