# Generated by Django 6.0.2 on 2026-08-23 09:09, then extended by hand with the
# data repair in the middle. See plans/PLAN_PLAYER_IDENTITY.md phase 1.

import django.db.models.functions.text
from coco_ratings.identity import canonical_player_number
from django.db import migrations, models

TEMP_PREFIX = "T-"
RESERVED = "BYE"


def _next_temp_minter(Player):
    """Return a callable minting fresh ``T-`` numbers, sequenced once.

    Scanning per row would be O(n^2) and, worse, would not see the numbers this
    same migration has just handed out.
    """
    highest = 0
    for number in Player.objects.filter(
        player_number__startswith=TEMP_PREFIX
    ).values_list("player_number", flat=True):
        try:
            highest = max(highest, int(number[len(TEMP_PREFIX):]))
        except (ValueError, TypeError):
            continue

    def mint():
        nonlocal highest
        highest += 1
        return f"{TEMP_PREFIX}{highest}"

    return mint


def canonicalize_and_repair(apps, schema_editor):
    """Make every player_number canonical and unique, so the constraint can land.

    Order matters and is the whole point of this function.

    **Canonicalization happens first.** These rows predate normalization, so the
    same person may appear as both ``233`` and ``0233``. De-duplicating first
    would compare raw strings, see two different keys, and leave both in place —
    one person permanently split in two, with nobody ever told. Canonicalizing
    first turns that into a visible collision, which is then reported distinctly
    from an ordinary duplicate because it means something different: an exact
    duplicate is a data-entry slip, whereas a collision *created* by
    canonicalization is almost certainly one human being with two rows, and
    merging those (they may each carry entrants and results) is a judgement call
    this migration must not make silently.

    Everything it cannot keep gets a fresh ``T-`` number rather than blocking the
    deploy, and every change is printed so the deploy log is the record.
    """
    Player = apps.get_model("tournaments", "Player")
    mint = _next_temp_minter(Player)
    report = []

    # Pass 1 - canonicalize in place. bulk_update, so Player.save() (which would
    # do this for us at runtime) is deliberately not involved.
    changed = []
    raw_before = {}
    for player in Player.objects.all():
        raw_before[player.pk] = player.player_number
        canonical = canonical_player_number(player.player_number)
        if canonical != player.player_number:
            player.player_number = canonical
            changed.append(player)
    if changed:
        Player.objects.bulk_update(changed, ["player_number"], batch_size=500)
        for player in changed:
            report.append(
                f"  canonicalized: {raw_before[player.pk]!r} -> "
                f"{player.player_number!r} ({player.name})"
            )

    # Pass 2 - resolve blanks, the reserved number, and collisions. Lowest pk
    # wins, so the oldest row keeps its number.
    seen = {}
    fixes = []
    for player in Player.objects.all().order_by("pk"):
        number = (player.player_number or "").strip()
        key = number.casefold()
        reason = None

        if not number:
            reason = "blank"
        elif key == RESERVED.casefold() and not player.is_bye:
            reason = f"held the reserved {RESERVED!r}"
        elif key in seen:
            keeper_pk, keeper_raw = seen[key]
            if keeper_raw == raw_before.get(player.pk):
                reason = f"duplicate of #{keeper_pk}"
            else:
                # Two different spellings that canonicalization merged.
                reason = (
                    f"SAME PERSON AS #{keeper_pk}? {raw_before.get(player.pk)!r} and "
                    f"{keeper_raw!r} both canonicalize to {number!r} - "
                    f"REVIEW AND MERGE BY HAND"
                )

        if reason is None:
            seen[key] = (player.pk, raw_before.get(player.pk))
            continue

        replacement = mint()
        report.append(
            f"  #{player.pk} {player.name!r}: {number!r} -> {replacement!r} ({reason})"
        )
        player.player_number = replacement
        player.is_provisional = True
        fixes.append(player)

    if fixes:
        Player.objects.bulk_update(
            fixes, ["player_number", "is_provisional"], batch_size=500
        )

    # Silent when there is nothing to say: this runs on every test database
    # too, and a per-run "nothing to repair" line is noise. A repair is the
    # exception, and the exception is what belongs in the deploy log.
    if report:
        print("\nPlayer number repair:")
        for line in report:
            print(line)


def noop_reverse(apps, schema_editor):
    """Nothing to undo: the repaired numbers are the correct ones, and the
    original spellings were ambiguous by definition."""


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0035_playoff"),
    ]

    operations = [
        # Widen first: the repair below may hand out T- numbers that would not
        # fit the old max_length=8 on a long-numbered install.
        migrations.AlterField(
            model_name="player",
            name="player_number",
            field=models.CharField(max_length=16),
        ),
        # Repair before the constraint, or adding it fails on existing data.
        migrations.RunPython(canonicalize_and_repair, noop_reverse),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("player_number"),
                name="unique_player_number_ci",
            ),
        ),
    ]
