# Generated by Django 6.0.2 on 2026-09-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0043_rostersync'),
    ]

    operations = [
        migrations.CreateModel(
            name='WespaSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Pulled by hand'), ('upload', 'Uploaded file')], max_length=16)),
                ('ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('added', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('unchanged', models.PositiveIntegerField(default=0)),
                ('rated', models.PositiveIntegerField(default=0)),
                ('linked', models.PositiveIntegerField(default=0)),
                ('pending', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='wespa_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='WespaPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wespa_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=8)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='tournaments_name_bd81b6_idx')],
            },
        ),
    ]
