# Generated by Django 6.0.2 on 2026-09-21 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0048_drop_resultslip_forfeit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('roster_pull', 'PlayerDB pull'), ('roster_resolution', 'Guest number confirmed'), ('wespa_pull', 'WESPA pull'), ('wespa_link', 'WESPA link'), ('wespa_unlink', 'WESPA unlink'), ('player_import', 'Player import'), ('player_merge', 'Guest merged'), ('password_set', 'Password set')], max_length=32)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('ok', models.BooleanField()),
                ('summary', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='tournaments_kind_858f57_idx')],
            },
        ),
    ]
