# Generated by Django 6.0.2 on 2026-09-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0049_admin_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='rostersync',
            name='repinned',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='wespasync',
            name='repinned',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
