import secrets

from coco_ratings.identity import canonical_player_number
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.functions import Lower
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify


def random_pairing_seed():
    """A fresh non-negative seed that fits both a signed BigInteger column and
    the Rust engine's u64 seed."""
    return secrets.randbelow(2**63)

# Slugs that would shadow a sibling static route's own detail page (the static
# routes themselves always win at request time thanks to URL ordering; this set
# only stops a generated slug from making an object's own page unreachable).
RESERVED_SLUGS = {"create", "fake-tournament", "create-player", "players"}


def unique_slug(base, queryset, max_length, fallback):
    """A unique slug for ``base``, deduped against ``queryset`` (which must
    already exclude the object being saved). A reserved or empty slugify result
    is treated as a collision and gets a numeric ``-2``/``-3``… suffix."""
    root = slugify(base)[:max_length] or fallback
    candidate = root
    n = 2
    while candidate in RESERVED_SLUGS or queryset.filter(slug=candidate).exists():
        suffix = f"-{n}"
        candidate = f"{root[:max_length - len(suffix)]}{suffix}"
        n += 1
    return candidate


def record_slug_alias(alias_model, *, scope, old_slug, new_slug, owner):
    """On rename, reclaim ``new_slug`` from any stale alias, then record
    ``old_slug`` as an alias pointing back at the renamed object.

    ``scope`` is the namespace filter (empty for the global tournament namespace,
    ``{"tournament": …}`` for the per-tournament division namespace); ``owner`` is
    the FK back to the object (e.g. ``{"division": self}``)."""
    alias_model.objects.filter(**scope, slug=new_slug).delete()
    alias_model.objects.update_or_create(**scope, slug=old_slug, defaults=owner)


class Tournament(models.Model):
    """A scrabble tournament."""

    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=220, unique=True, editable=False)
    location = models.CharField(max_length=200)
    start_date = models.DateField()
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="owned_tournaments",
    )
    editors = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="editable_tournaments",
        blank=True,
    )
    # True for tournaments generated by the fake-tournament tool (random players,
    # auto-simulated rounds). Used to offer a delete link and to let admins, not
    # just the owner, clean them up.
    is_fake = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-start_date"]

    def __str__(self):
        return self.name

    def slug_kwargs(self):
        """URL kwargs identifying this tournament. Spread into ``reverse``/
        ``redirect`` for any tournament-scoped route."""
        return {"tournament_slug": self.slug}

    def save(self, *args, **kwargs):
        old_slug = self.slug if self.pk else None
        self.slug = unique_slug(
            self.name, Tournament.objects.exclude(pk=self.pk), 220, "tournament"
        )
        if kwargs.get("update_fields") is not None:
            kwargs["update_fields"] = set(kwargs["update_fields"]) | {"slug"}
        super().save(*args, **kwargs)
        if old_slug and old_slug != self.slug:
            record_slug_alias(
                TournamentSlugAlias, scope={},
                old_slug=old_slug, new_slug=self.slug, owner={"tournament": self},
            )

    def get_absolute_url(self):
        return reverse("tournament_detail", kwargs=self.slug_kwargs())

    def can_edit(self, user):
        """Check if user can edit this tournament. Anonymous users always return False.

        Supervisors and above hold director-level access to *every* tournament.
        That membership is silent by design: it is derived here rather than
        stored, so it never appears in ``editors`` — not on the tournament page,
        not in the edit form, and not in the event log, which records only the
        editors a director actually named. A role change takes effect everywhere
        at once, and revoking it revokes it everywhere.
        """
        if not user.is_authenticated:
            return False
        from users.models import User
        if user.has_role_at_least(User.Role.SUPERVISOR):
            return True
        return user == self.owner or self.editors.filter(pk=user.pk).exists()

    def can_delete(self, user):
        """Who may delete this tournament. The owner always may; admins may delete
        fake tournaments (the cleanup path), but not real ones."""
        if not user.is_authenticated:
            return False
        if user == self.owner:
            return True
        if not self.is_fake:
            return False
        from users.models import User
        return user.has_role_at_least(User.Role.ADMIN)

    def division_buckets(self):
        """Return divisions grouped into regular, test, and deleted lists."""
        return {
            "regular_divisions": self.divisions.filter(is_test=False),
            "test_divisions": self.divisions.filter(is_test=True),
            "deleted_divisions": Division.all_objects.filter(
                tournament=self, is_deleted=True
            ),
        }


class ActiveDivisionManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)


class Division(models.Model):
    """A division within a tournament."""

    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=120, editable=False)
    tournament = models.ForeignKey(
        Tournament,
        on_delete=models.CASCADE,
        related_name="divisions",
    )
    is_test = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    deleted_at = models.DateTimeField(null=True, blank=True)

    objects = ActiveDivisionManager()
    all_objects = models.Manager()

    class Meta:
        ordering = ["name"]
        unique_together = [["tournament", "name"], ["tournament", "slug"]]

    def __str__(self):
        return self.name

    def slug_kwargs(self):
        """URL kwargs identifying this division: its tournament and own slug.
        Spread into ``reverse``/``redirect`` for any division-scoped route."""
        return {"tournament_slug": self.tournament.slug, "division_slug": self.slug}

    def save(self, *args, **kwargs):
        old_slug = self.slug if self.pk else None
        self.slug = unique_slug(
            self.name,
            # all_objects so a soft-deleted sibling's slug isn't reused.
            Division.all_objects.filter(tournament=self.tournament).exclude(pk=self.pk),
            120,
            "division",
        )
        if kwargs.get("update_fields") is not None:
            kwargs["update_fields"] = set(kwargs["update_fields"]) | {"slug"}
        super().save(*args, **kwargs)
        if old_slug and old_slug != self.slug:
            record_slug_alias(
                DivisionSlugAlias, scope={"tournament": self.tournament},
                old_slug=old_slug, new_slug=self.slug, owner={"division": self},
            )

    def soft_delete(self):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

    def restore(self):
        self.is_deleted = False
        self.deleted_at = None
        self.save()

    def max_round(self):
        return (
            self.result_slips.aggregate(max_round=models.Max("round"))["max_round"] or 0
        )

    def bye_entrant(self):
        """Get or create this division's bye entrant (one per division, all
        referencing the singleton bye Player). Hidden from ``entrants`` by the
        default manager; used as the opponent in a bye pairing/result."""
        bye, _ = Entrant.all_objects.get_or_create(
            division=self,
            player=Player.get_bye(),
            defaults={"number": 0},
        )
        return bye

    def pairings_by_round_pair(self):
        """Return {(round, frozenset({first_id, second_id})): Pairing} for all pairings."""
        return {
            (p.round, frozenset({p.first_id, p.second_id})): p
            for p in self.pairings.all()
        }

    def configured_round_numbers(self, default=range(1, 16)):
        """Return sorted round numbers configured in DivisionSettings, or a default range."""
        try:
            rps = self.settings.round_pairings
            return sorted({rp["round"] for rp in rps})
        except AttributeError, KeyError, TypeError, DivisionSettings.DoesNotExist:
            return list(default)


class TournamentSlugAlias(models.Model):
    """A previous slug of a tournament, kept so its old-slug URLs can 301-redirect
    to the current slug after a rename."""

    tournament = models.ForeignKey(
        Tournament, on_delete=models.CASCADE, related_name="slug_aliases"
    )
    slug = models.SlugField(max_length=220, unique=True)

    def __str__(self):
        return self.slug


class DivisionSlugAlias(models.Model):
    """A previous slug of a division (per-tournament namespace); see
    :class:`TournamentSlugAlias`."""

    division = models.ForeignKey(
        Division, on_delete=models.CASCADE, related_name="slug_aliases"
    )
    tournament = models.ForeignKey(
        Tournament, on_delete=models.CASCADE, related_name="division_slug_aliases"
    )
    slug = models.SlugField(max_length=120)

    class Meta:
        unique_together = ["tournament", "slug"]

    def __str__(self):
        return self.slug


# Default COP prize/tuning config. Seeded when a COP schedule is saved, or
# lazily on first pairing for imported/legacy schedules, and used as the
# settings form's field defaults so the two never drift.
DEFAULT_COP_CONFIG = {
    "place_prizes": 3,
    "gibson_spread": 500,
    "hopefulness": 0.05,
    "control_loss_threshold": 0.25,
    "control_loss_activation_round": 0,
    "simulations": 1000,
    "always_wins_simulations": 1000,
    "disallow_repeat_byes": True,
}


def default_cop_config() -> dict:
    """A fresh copy of the default COP config."""
    return dict(DEFAULT_COP_CONFIG)


# Tuning for the Swiss family (Swiss, SwissPlusRandom). These were hardcoded in
# the engine; the values here are those constants, so an empty config pairs
# exactly as before. The Google Sheets script Baxter's Swiss was ported from
# exposes swiss_weight and swiss_distance, and uses swiss_distance for *both*
# max_distance and spr_split — set the two equal to reproduce a sheet.
DEFAULT_SWISS_CONFIG = {
    # Cost of a repeat pairing, relative to one place of standings distance.
    "swiss_weight": 30,
    # Don't pair candidates this many places apart or more.
    "max_distance": 11,
    # SwissPlusRandom: size of the Swiss-paired top slice; the rest go random.
    "spr_split": 10,
}


def default_swiss_config() -> dict:
    """A fresh copy of the default Swiss config."""
    return dict(DEFAULT_SWISS_CONFIG)


class DivisionSettings(models.Model):
    """Settings for a division."""

    division = models.OneToOneField(
        Division,
        on_delete=models.CASCADE,
        related_name="settings",
    )
    round_pairings = models.JSONField(default=list)
    board_table_map = models.JSONField(default=list)
    # Source of truth for the round-pairings editor; round_pairings is derived
    # from it. Each block: {"pairing", "rounds", "pair_from"}.
    pairing_blocks = models.JSONField(default=list)
    # Seed for the pairing engine's random strategies, stable across regenerations
    # so lazy draft re-pairing doesn't reshuffle random rounds on every render.
    # Re-rolled only by an explicit reshuffle action.
    pairing_seed = models.BigIntegerField(default=random_pairing_seed)
    # Prize + tuning config for the COP pairing strategy. Empty unless a round
    # uses COP. Scalar-valued (place_prizes, gibson_spread, hopefulness,
    # control_loss_threshold, control_loss_activation_round, simulations,
    # always_wins_simulations, disallow_repeat_byes); the engine adapter expands
    # the per-round-array fields. See tournaments/pairing/engine.py.
    cop_config = models.JSONField(default=dict)
    # Tuning for the Swiss family (swiss_weight, max_distance, spr_split). Empty
    # means the engine's built-in defaults, which are DEFAULT_SWISS_CONFIG.
    swiss_config = models.JSONField(default=dict)

    def __str__(self):
        return f"Settings for {self.division}"


# Reserved namespace for player numbers minted locally in Baxter for players
# that are not yet known to the registry. The hyphen guarantees these never
# collide with canonical registry numbers, and it makes them non-numeric, so
# canonical_player_number leaves them alone. The registry never receives them:
# a tournament export blocks until an admin has assigned real numbers centrally
# and Baxter has pulled them (see plans/PLAN_COCO_PROGRAM.md).
TEMP_NUMBER_PREFIX = "T-"


def next_temp_player_number():
    """Generate the next temporary player number for a locally-created player.

    Numbers live in the reserved ``T-`` namespace and are sequenced over the
    existing provisional players only, so they never clash with registry numbers.
    """
    max_n = 0
    for number in Player.objects.filter(
        is_provisional=True, player_number__startswith=TEMP_NUMBER_PREFIX
    ).values_list("player_number", flat=True):
        try:
            max_n = max(max_n, int(number[len(TEMP_NUMBER_PREFIX) :]))
        except ValueError:
            continue
    return f"{TEMP_NUMBER_PREFIX}{max_n + 1}"


# The singleton bye player's name and reserved number. The engine recognises a
# bye by name (Player.is_bye → name == "bye"), so this name must stay "Bye".
#
# BYE_PLAYER_NUMBER is reserved: once player_number is the engine key
# (plans/PLAN_PLAYER_IDENTITY.md), a real player holding "BYE" would be paired
# as the bye. It is non-numeric, so canonicalization leaves it untouched.
BYE_PLAYER_NAME = "Bye"
BYE_PLAYER_NUMBER = "BYE"


def is_reserved_player_number(number):
    """True for the bye's reserved number, in any casing.

    Bye detection is case-insensitive on both sides of the engine boundary
    (``scrabble-pairing/src/standings.rs`` compares with
    ``eq_ignore_ascii_case``), so the reservation has to be too.
    """
    return str(number or "").strip().casefold() == BYE_PLAYER_NUMBER.casefold()


def effective_rating(rating, wespa_rating):
    """``(rating, source)`` — CoCo, else WESPA, else 0.

    **The one place this cascade lives.** It is a free function rather than a
    method because two things need it and only one of them is a model:
    ``Player.effective_rating`` below, and ``player_source.PlayerRecord``, which
    describes a player some other source is offering and holds no model at all.
    That second one used to re-derive the cascade line for line under a
    docstring saying nothing may — which is how a rule ends up with two versions
    and one of them wrong.

    A CoCo rating of 0 means "no CoCo rating" — Baxter's long-standing spelling
    of it — so it falls through. A WESPA rating of 0 does not: NULL is how that
    one says "not known" (plans/PLAN_ENTRANTS.md decision 2).
    """
    if rating:
        return rating, Entrant.COCO
    if wespa_rating is not None:
        return wespa_rating, Entrant.WESPA
    return 0, Entrant.NONE


class Player(models.Model):
    """A tournament player.

    ``player_number`` is the identity — not ``name``. Names are not unique in
    the real world, and everything outside the database (the pairing engine,
    event payloads, the digest, the interchange with the central player
    database) keys on the number. See plans/PLAN_PLAYER_IDENTITY.md.
    """

    name = models.CharField(max_length=200)
    # Canonical form is the central database's: zero-padded to four digits
    # ("0233"). Wider than the 4 that form needs, because Baxter also stores
    # "T-" placeholders for players the central database has not numbered yet.
    player_number = models.CharField(max_length=16)
    # The CoCo rating, and what the central roster pull writes. 0 means "no CoCo
    # rating" — the sole test for it (see plans/PLAN_ENTRANTS.md decision 2).
    # Deliberately not renamed to coco_rating: every existing payload key,
    # export field, grid DTO and replay path uses this name.
    rating = models.IntegerField()
    # The WESPA rating, which is nobody else's business: it never syncs to the
    # central database and is only consulted when there is no CoCo rating.
    # NULL means "not known", which is distinct from a rating of 0.
    wespa_rating = models.IntegerField(null=True, blank=True)
    # Which row of the WESPA mirror this player is, if anyone has said. Set
    # when a guest is minted from a WESPA row (a human picked it) or when a
    # name is unique on both sides; left NULL when it would be a guess. Once
    # set it is what a pull matches on, so a player who is spelled differently
    # in the two lists keeps working. See plans/PLAN_WESPA.md decision 3.
    wespa_id = models.IntegerField(null=True, blank=True, unique=True)

    # The rest of the rating seed, mirrored from the central roster alongside
    # ``rating``. The live rating projection needs all four: the calculator
    # damps by career games, and deviation grows with time since last_played.
    #
    # These live here rather than only on Entrant because an entrant *freezes*
    # them at registration (plans/PLAN_COCO_PROGRAM.md decision 6) — so they
    # need a place to sit between a roster pull and the next person entered.
    # NULL means the roster has never told us, which the calculator reads as an
    # unrated player.
    deviation = models.FloatField(null=True, blank=True)
    career_games = models.IntegerField(default=0)
    last_played = models.DateField(null=True, blank=True)
    # True for players created locally that the registry has not yet seen; their
    # player_number is a temporary T- value the registry replaces on upload.
    is_provisional = models.BooleanField(default=False)
    # The single synthetic "bye" opponent. Exactly one such Player exists (see
    # get_bye); it is never sent to the registry and never shown as a competitor.
    is_bye = models.BooleanField(default=False)

    class Meta:
        ordering = ["name"]
        constraints = [
            # Uniqueness is on the *canonical* form. canonical_player_number
            # already collapses 233/0233/00233 onto one key, so what is left for
            # the index to catch is case: the non-numeric keys ("T-7", "BYE")
            # pass through canonicalization untouched, and bye detection is
            # case-insensitive on both sides of the engine boundary.
            models.UniqueConstraint(
                Lower("player_number"), name="unique_player_number_ci"
            )
        ]

    def __str__(self):
        return self.name

    def clean(self):
        super().clean()
        if is_reserved_player_number(self.player_number) and not self.is_bye:
            raise ValidationError(
                {"player_number": f"'{BYE_PLAYER_NUMBER}' is reserved for the bye."}
            )

    def save(self, *args, **kwargs):
        """Normalize the number on the way in, so the stored key is canonical by
        construction.

        This mirrors the central database, which funnels every write through the
        same function. One un-normalized write is enough to split a person into
        two identities, and ``objects.create``, the admin and the shell all come
        through here. ``bulk_create``/``bulk_update`` bypass ``save`` as they
        always do — the migration that backfills canonical numbers calls
        ``canonical_player_number`` directly for that reason.
        """
        self.player_number = canonical_player_number(self.player_number)
        super().save(*args, **kwargs)

    @classmethod
    def get_bye(cls):
        """Return the singleton bye player, creating it once if needed."""
        player, _ = cls.objects.get_or_create(
            is_bye=True,
            defaults={
                "name": BYE_PLAYER_NAME,
                "player_number": BYE_PLAYER_NUMBER,
                "rating": 0,
                "is_provisional": True,
            },
        )
        return player

    @property
    def effective_rating(self):
        """``(rating, source)`` — CoCo, else WESPA, else 0.

        An entrant snapshots the result at entry (``Entrant.enter``) so a later
        drift in either rating cannot reshuffle a running tournament.
        """
        return effective_rating(self.rating, self.wespa_rating)

    @classmethod
    def same_named(cls, name):
        """Existing players with this name, case-insensitively.

        Sharing a name is legal — the number is the identity — but it is far
        more often a typo than two real people, so the create flow shows these
        and asks rather than either refusing or silently adding a twin.
        """
        name = (name or "").strip()
        if not name:
            return cls.objects.none()
        return cls.objects.filter(name__iexact=name).order_by("player_number")

    @classmethod
    def create(cls, name, rating=0):
        """Create a Player with an auto-assigned temporary number.

        Returns (player, error_message). The name is not checked for uniqueness:
        two people may genuinely share one. Callers that want the director to
        confirm a duplicate ask ``same_named`` first.
        """
        name = (name or "").strip()
        if not name:
            return None, "Name is required."
        try:
            rating = int(rating)
        except ValueError, TypeError:
            rating = 0
        player = cls.objects.create(
            name=name,
            player_number=next_temp_player_number(),
            rating=rating,
            is_provisional=True,
        )
        return player, None


class RealEntrantManager(models.Manager):
    """Default manager that hides the synthetic bye entrant.

    Every ``division.entrants`` query (the reverse relation uses this manager)
    therefore sees only real competitors, so the bye never appears in rosters,
    counts, edit grids, exports, or pairing data. The bye entrant is reached
    explicitly via ``Entrant.all_objects`` / ``Division.bye_entrant`` and through
    forward FK access (``pairing.first``), which uses the unfiltered base manager.
    """

    def get_queryset(self):
        return super().get_queryset().filter(player__is_bye=False)


class Entrant(models.Model):
    """A player entered in a division, with their registration state."""

    # Where the pinned rating came from. NONE is "no rating at all", which is
    # not the same as a rating that happens to be 0 — a rated player can be on
    # zero, an unrated one has nothing.
    COCO, WESPA, MANUAL, NONE = "coco", "wespa", "manual", "none"
    RATING_SOURCES = [
        (COCO, "CoCo"),
        (WESPA, "WESPA"),
        (MANUAL, "Manual"),
        (NONE, "None"),
    ]

    division = models.ForeignKey(
        Division,
        on_delete=models.CASCADE,
        related_name="entrants",
    )
    player = models.ForeignKey(
        Player,
        on_delete=models.CASCADE,
        related_name="entries",
    )
    # The entrant's number *for this tournament* — a seeding, not a physical
    # seat or board. It is derived from the pinned rating (highest rated is 1)
    # while the division is still in draft, and frozen once a round has been
    # published, so a late entrant is appended rather than reshuffling everyone
    # else's. Nothing pairs off it: the engine keys on rating, and this is what
    # breaks a tie between equal ratings and what the standings show in
    # brackets. See ``reseed`` below.
    number = models.IntegerField()
    # A dropped (withdrawn) entrant is excluded from all future pairing but keeps
    # their played results, which still count for everyone else's standings,
    # repeats, and spread. Finished rounds are never re-paired, so a boolean is
    # enough — we never need to know *when* they withdrew.
    dropped = models.BooleanField(default=False)

    # -- the pinned rating (decision 3) ------------------------------------
    #
    # Snapshotted at entry, never re-derived. Seeding, display and replay read
    # this, so Player.rating and Player.wespa_rating are free to drift under a
    # running tournament without reshuffling anyone's pairings — which is also
    # what lets a global rating refresh stay an unlogged action.
    rating = models.IntegerField(default=0)
    rating_source = models.CharField(
        max_length=8, choices=RATING_SOURCES, default=NONE
    )
    # The rest of the rating seed, frozen with the rating. The live rating
    # projection needs all four: the calculator damps by career games, and
    # deviation grows with time since last_played. Zero/null until the central
    # roster pull exists, which the calculator reads as an unrated player.
    deviation = models.FloatField(default=0.0)
    career_games = models.IntegerField(default=0)
    last_played = models.DateField(null=True, blank=True)

    # -- registration state -------------------------------------------------
    #
    # tentative: entered but not confirmed (issue #42). Its own field rather
    # than a derivation of `paid`, because an organizer may confirm an unpaid
    # entrant or hold a paid one.
    tentative = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    # Editor-only, never rendered publicly. Free text on purpose: no amounts, no
    # methods, no fee schedule (decision 6).
    payment_note = models.TextField(blank=True, default="")
    # Playing above their rating band — a judgement call an organizer ticks, not
    # something derived from a band on the division (decision 7).
    playing_up = models.BooleanField(default=False)

    objects = RealEntrantManager()
    all_objects = models.Manager()

    class Meta:
        ordering = ["number"]
        unique_together = [("division", "number"), ("division", "player")]
        base_manager_name = "all_objects"

    def __str__(self):
        return f"{self.number}: {self.player.name}"

    @property
    def name(self):
        return self.player.name

    @property
    def key(self):
        """The entrant's identity for the pairing layer — never the name."""
        return self.player.player_number

    @staticmethod
    def is_rating_override(pinned, submitted):
        """Whether ``submitted`` is a director overriding ``pinned`` by hand.

        The rule both editing surfaces need, in one place. Every form that can
        edit a rating pre-fills it with the value already pinned, so treating a
        value's mere *presence* as an override would flip an entrant to
        ``manual`` on any save that touched anything at all — silently making
        them immune to a later sync. Only an actual change is an override.

        Blank is never an override: on the registration page it means "use the
        player's own rating", and in the grid it means the column was not
        touched.
        """
        return submitted is not None and submitted != pinned

    @classmethod
    def next_number(cls, division):
        """The number a new entrant takes when the seeding is frozen."""
        return (
            cls.all_objects.filter(division=division).aggregate(
                m=models.Max("number")
            )["m"] or 0
        ) + 1

    @classmethod
    def seeding_for(cls, division):
        """``[[player_number, n], …]`` — this division in rating order.

        Highest rating is 1. Ties break on the player number, because a tie has
        to break on *something* and the number is the identity everywhere else
        outside the database (PLAN_PLAYER_IDENTITY.md). Anything less
        deterministic would make a replay's numbering depend on row order.

        Withdrawn entrants are numbered along with everyone else: they keep
        their place in the field they entered, and their results still count.

        Two other places order a field and must not drift from this one:
        ``views.entrants_for_display`` reads the number this writes, and
        ``pairing.base.seedings`` re-sorts by rating with the order
        ``PairingData`` was built in as its tiebreak — which is this order.
        """
        entrants = sorted(
            cls.all_objects.filter(division=division).select_related("player"),
            key=lambda e: (-e.rating, e.player.player_number),
        )
        return [[e.player.player_number, i] for i, e in enumerate(entrants, 1)]

    @classmethod
    def apply_seeding(cls, division, seeding):
        """Write a ``seeding_for``-shaped list. Returns the entrants changed.

        Done in two passes through negative numbers. ``(division, number)`` is
        unique, so assigning the final numbers directly would collide the moment
        two entrants swap places — and a swap is the common case, not a corner
        one.
        """
        by_key = {
            e.player.player_number: e
            for e in cls.all_objects.filter(division=division).select_related("player")
        }
        changed = []
        for key, number in seeding:
            entrant = by_key.get(key)
            if entrant is None:
                raise ValueError(
                    f"No entrant with player number {key!r} in {division.name}."
                )
            if entrant.number != number:
                changed.append((entrant, number))
        if not changed:
            return []
        for i, (entrant, _) in enumerate(changed, 1):
            cls.all_objects.filter(pk=entrant.pk).update(number=-i)
        for entrant, number in changed:
            cls.all_objects.filter(pk=entrant.pk).update(number=number)
            entrant.number = number
        return [entrant for entrant, _ in changed]

    @classmethod
    def enter(
        cls, division, player, number, *, rating=None, rating_source=None,
        **registration,
    ):
        """Enter ``player`` in ``division``, pinning their rating.

        The rating is snapshotted from ``Player.effective_rating`` unless one is
        passed explicitly, which marks it ``manual`` and immune to any later
        sync. This is deliberately *not* done in ``save()``: that would fire on
        every unrelated write and silently re-pin a rating a director had fixed
        by hand.

        ``rating_source`` overrides that derivation, and exists for one caller:
        replay, which is restoring a snapshot rather than making a decision. A
        recorded ``(0, "none")`` must come back as ``none``, not as the
        ``manual`` that passing a rating would otherwise imply.
        """
        if rating_source is not None:
            source = rating_source
            rating = rating or 0
        elif rating is None:
            rating, source = player.effective_rating
        else:
            source = cls.MANUAL
        # The rest of the seed is frozen with the rating, and always from the
        # player: a director overriding a rating by hand is saying what this
        # player is worth, not rewriting their playing history.
        registration.setdefault("deviation", player.deviation or 0.0)
        registration.setdefault("career_games", player.career_games)
        registration.setdefault("last_played", player.last_played)
        return cls.objects.create(
            division=division,
            player=player,
            number=number,
            rating=rating,
            rating_source=source,
            **registration,
        )

    @property
    def display_name(self):
        """The name as it should be shown, disambiguated if it has to be.

        Falls back to the bare name. ``tournaments.display.label_entrants``
        sets it per instance where a scope is known, so a template gets the
        disambiguated label there and the plain name everywhere else. The value
        is kept under a private key because a property is a data descriptor and
        would otherwise win over anything put in ``__dict__``.
        """
        return self.__dict__.get("_display_name") or self.player.name

    @display_name.setter
    def display_name(self, value):
        self.__dict__["_display_name"] = value


class ResultSlip(models.Model):
    """A game result slip."""

    division = models.ForeignKey(
        Division,
        on_delete=models.CASCADE,
        related_name="result_slips",
    )
    round = models.IntegerField()
    pairing = models.OneToOneField(
        "Pairing",
        on_delete=models.SET_NULL,
        related_name="result",
        null=True,
        blank=True,
    )
    winner = models.ForeignKey(
        Entrant,
        on_delete=models.CASCADE,
        related_name="wins",
    )
    winner_score = models.IntegerField()
    loser = models.ForeignKey(
        Entrant,
        on_delete=models.CASCADE,
        related_name="losses",
    )
    loser_score = models.IntegerField()
    winner_started = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        ordering = ["round"]

    @property
    def winner_name(self):
        return self.winner.player.name

    @property
    def loser_name(self):
        return self.loser.player.name

    @property
    def winner_key(self):
        return self.winner.player.player_number

    @property
    def loser_key(self):
        return self.loser.player.player_number

    def to_dict(self):
        return {
            "id": self.pk,
            "round": self.round,
            "winner": self.winner_id,
            "winner_score": self.winner_score,
            "loser": self.loser_id,
            "loser_score": self.loser_score,
            "winner_started": self.winner_started,
        }

    def __str__(self):
        return f"R{self.round}: {self.winner_name} {self.winner_score}-{self.loser_score} {self.loser_name}"


class RoundPairingsQuerySet(models.QuerySet):
    def revert_published_to_draft(self, round_numbers=None):
        """Move PUBLISHED rounds back to DRAFT so they can be regenerated.

        If ``round_numbers`` is provided, the change is scoped to those rounds.
        Caller is responsible for confirming none of these rounds have results.
        """
        qs = self.filter(status=RoundPairings.PUBLISHED)
        if round_numbers is not None:
            if not round_numbers:
                return 0
            qs = qs.filter(round__in=round_numbers)
        return qs.update(status=RoundPairings.DRAFT)


class RoundPairings(models.Model):
    """Lifecycle container for all pairings in a division round."""

    DRAFT = "draft"
    PUBLISHED = "published"
    IN_PROGRESS = "in_progress"
    FINISHED = "finished"
    STATUS_CHOICES = [
        (DRAFT, "Draft"),
        (PUBLISHED, "Published"),
        (IN_PROGRESS, "In Progress"),
        (FINISHED, "Finished"),
    ]

    division = models.ForeignKey(
        Division,
        on_delete=models.CASCADE,
        related_name="round_pairings_set",
    )
    round = models.IntegerField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=DRAFT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    objects = RoundPairingsQuerySet.as_manager()

    class Meta:
        unique_together = ["division", "round"]
        ordering = ["round"]

    def __str__(self):
        return f"R{self.round} ({self.get_status_display()}) - {self.division}"

    def update_status(self):
        """Recompute lifecycle status from the current count of results."""
        total = self.pairings.count()
        with_results = self.pairings.filter(result__isnull=False).count()
        # A bye is auto-recorded at publish time but isn't a played game, so it
        # doesn't make a round "in progress" — only a real (non-bye) result does.
        # Byes still count toward `with_results` for reaching FINISHED below.
        real_results = self.pairings.filter(result__isnull=False).exclude(
            result__loser__player__is_bye=True
        ).count()
        if (
            total > 0
            and with_results == total
            and self.status in (RoundPairings.PUBLISHED, RoundPairings.IN_PROGRESS)
        ):
            # Tested first so a single call can settle the round outright. When
            # the last missing result is a bye, `real_results < total` is also
            # true, and checking that first would stop at IN_PROGRESS — leaving a
            # fully played round stuck there until something happened to call
            # this again, which for a batch-entered round nothing does.
            #
            # `total > 0` guards against an unpaired round (e.g. a round-robin
            # block round created up front but not yet paired): with no pairings
            # `with_results == total` is vacuously true, which would otherwise
            # mark a round with no games as finished.
            self.status = RoundPairings.FINISHED
            self.save(update_fields=["status"])
        elif real_results == 0 and self.status == RoundPairings.IN_PROGRESS:
            self.status = RoundPairings.PUBLISHED
            self.save(update_fields=["status"])
        elif 0 < real_results < total and self.status == RoundPairings.PUBLISHED:
            self.status = RoundPairings.IN_PROGRESS
            self.save(update_fields=["status"])


class Pairing(models.Model):
    """A generated pairing for a division round."""

    division = models.ForeignKey(
        Division,
        on_delete=models.CASCADE,
        related_name="pairings",
    )
    round = models.IntegerField()
    round_pairings = models.ForeignKey(
        RoundPairings,
        on_delete=models.CASCADE,
        related_name="pairings",
        null=True,
        blank=True,
    )
    first = models.ForeignKey(
        Entrant,
        on_delete=models.CASCADE,
        related_name="pairings_as_first",
    )
    second = models.ForeignKey(
        Entrant,
        on_delete=models.CASCADE,
        related_name="pairings_as_second",
    )
    repeats = models.IntegerField(default=0)
    # ``table`` is the integer order index (also groups boards that share a
    # physical double table). ``table_label`` is the display string shown to
    # organizers (e.g. "S1" for a streamed table); empty falls back to ``table``.
    table = models.IntegerField(default=0)
    table_label = models.CharField(max_length=8, default="", blank=True)
    # Set on a playoff game: which series it belongs to and its 1-based game
    # number within that series. Null for every ordinary pairing.
    series = models.ForeignKey(
        "PlayoffSeries",
        on_delete=models.SET_NULL,
        related_name="pairings",
        null=True,
        blank=True,
    )
    game_number = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ["round", "table"]

    def __str__(self):
        return f"R{self.round}: {self.first.name} vs. {self.second.name}"


class FixedPairing(models.Model):
    """A fixed (pre-set) pairing for a division round."""

    division = models.ForeignKey(
        Division, on_delete=models.CASCADE, related_name="fixed_pairings"
    )
    round_number = models.IntegerField()
    entrant1 = models.ForeignKey(
        Entrant, on_delete=models.CASCADE, related_name="fixed_pairings_as_first"
    )
    entrant2 = models.ForeignKey(
        Entrant, on_delete=models.CASCADE, related_name="fixed_pairings_as_second"
    )

    class Meta:
        ordering = ["round_number"]

    def __str__(self):
        return f"R{self.round_number}: {self.entrant1.name} vs. {self.entrant2.name}"


class FixedTable(models.Model):
    """A fixed (pre-set) table assignment for an entrant in a division round."""

    division = models.ForeignKey(
        Division, on_delete=models.CASCADE, related_name="fixed_tables"
    )
    round_number = models.IntegerField()
    entrant = models.ForeignKey(
        Entrant, on_delete=models.CASCADE, related_name="fixed_tables"
    )
    # The display label of the table this entrant is pinned to (e.g. "S1", "4").
    table_label = models.CharField(max_length=8)

    class Meta:
        ordering = ["round_number", "table_label"]

    def __str__(self):
        return f"R{self.round_number}: {self.entrant.player.name} at table {self.table_label}"


class Playoff(models.Model):
    """A championship playoff attached to a division.

    Holds only the director's *intent*: which round qualifies, how many
    qualifiers, the timing mode, the length of each series, and the confirmed
    seed snapshot. The bracket itself — who meets whom, series scores, which
    games still need playing, final placements — is derived from this plus the
    division's results by ``tournaments/playoff.py``, never stored. See
    ``plans/PLAN_PLAYOFFS.md``.
    """

    POSTSCRIPT = "postscript"
    CONCURRENT = "concurrent"
    TIMING_CHOICES = [
        (POSTSCRIPT, "Postscript"),
        (CONCURRENT, "Concurrent"),
    ]

    division = models.OneToOneField(
        Division, on_delete=models.CASCADE, related_name="playoff"
    )
    # Seeds come from the standings after this round.
    qualification_round = models.IntegerField()
    qualifier_count = models.IntegerField()
    timing = models.CharField(max_length=20, choices=TIMING_CHOICES, default=POSTSCRIPT)
    # Series key -> maximum games (see playoff.SERIES_LABELS). A placement key
    # that is missing or 0 means that series is not played.
    stage_games = models.JSONField(default=dict)
    # The confirmed qualifiers, best seed first, as recorded at creation:
    # [{"seed": 1, "key": "0233", "player": "…", "wins": 5.0, "spread": 412}, …].
    # ``key`` is the player number — the identity the bracket derives from —
    # and ``player`` is carried alongside it so the snapshot stays readable and
    # the qualifiers table needs no lookup. Both are portable (no pks), so this
    # replays into a fresh database. Frozen here so an exact tie in the
    # qualification standings is resolved once, by the director, rather than
    # re-derived from an unstable sort.
    seeds = models.JSONField(default=list)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.qualifier_count}-player playoff — {self.division}"

    def config(self):
        """The plain-data config the derivation takes."""
        from tournaments.playoff import PlayoffConfig

        return PlayoffConfig.from_model(self)

    def bracket(self, slips=None):
        """The derived bracket. Pass ``slips`` to reuse an existing queryset."""
        from tournaments.playoff import build_bracket

        if slips is None:
            slips = self.division.result_slips.select_related(
                "winner__player", "loser__player"
            )
        return build_bracket(self.config(), slips)


class PlayoffSeries(models.Model):
    """One series in a playoff bracket — structure only.

    Derived rows, like ``RoundPairings``: the pairing generator upserts them on
    ``(playoff, key, position)`` and never deletes them while the playoff
    exists, so a ``Pairing.series`` reference stays valid. Score, winner, loser
    and status are deliberately absent: they are computed from results.
    """

    playoff = models.ForeignKey(
        Playoff, on_delete=models.CASCADE, related_name="series"
    )
    # A ``tournaments.playoff`` series key: "semifinal", "championship", …
    key = models.CharField(max_length=32)
    position = models.IntegerField(default=0)
    # The better-seeded participant, once known.
    high = models.ForeignKey(
        Entrant,
        on_delete=models.CASCADE,
        related_name="playoff_series_as_high",
        null=True,
        blank=True,
    )
    low = models.ForeignKey(
        Entrant,
        on_delete=models.CASCADE,
        related_name="playoff_series_as_low",
        null=True,
        blank=True,
    )
    max_games = models.IntegerField(default=1)
    # First round of this series' stage window.
    start_round = models.IntegerField()

    class Meta:
        unique_together = [("playoff", "key", "position")]
        ordering = ["start_round", "key", "position"]

    def __str__(self):
        return f"{self.key} {self.position} ({self.playoff.division})"


# The bulk-editable grids. Used as the ``scope`` half of the editgrid key
# (see ``edit_key`` in views) for the optimistic-concurrency token and editing
# presence, both of which now live in the reusable ``editgrid`` app.
EDIT_SCOPES = frozenset(
    {
        "entrants",
        "results",
        "fixed_pairings",
        "fixed_tables",
        "board_table_map",
        "round_pairings",
    }
)


class TournamentEvent(models.Model):
    """One entry in a tournament's append-only event log.

    Records the *inputs* of a state-changing command (never the resulting rows);
    derived state is recomputed on replay. Append-only: there are no update or
    delete code paths (deleting a tournament cascades its log). The catalog of
    valid ``event_type`` values and the recording machinery live in
    ``tournaments/events.py``.
    """

    tournament = models.ForeignKey(
        Tournament, on_delete=models.CASCADE, related_name="events"
    )
    seq = models.PositiveIntegerField()  # 1-based, contiguous per tournament
    created_at = models.DateTimeField(auto_now_add=True)
    # Null actor = anonymous (e.g. a player submitting a result); the hashed
    # session key still identifies the browser for the audit trail.
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True
    )
    actor_session = models.CharField(max_length=64, blank=True)
    # Convenience filter only — the payload carries the division *name*, which is
    # what replay keys on (this FK is nulled if the division is later deleted).
    division = models.ForeignKey(
        Division, on_delete=models.SET_NULL, null=True, blank=True
    )
    event_type = models.CharField(max_length=50)
    schema_version = models.PositiveSmallIntegerField(default=1)
    payload = models.JSONField()
    # sha256 of the affected division's canonical state after the command, so a
    # replay can compare digests per event and pinpoint the first divergence.
    digest = models.CharField(max_length=64, blank=True)

    class Meta:
        unique_together = [["tournament", "seq"]]
        ordering = ["tournament", "seq"]

    def __str__(self):
        return f"{self.tournament} #{self.seq} {self.event_type}"


class RosterSync(models.Model):
    """The outcome of one pull of the central roster.

    A scheduled pull has nobody watching it. Without a record, two things go
    silent: rows the pull holds back for a human to confirm would evaporate
    (they used to live in the puller's session, which a cron run does not have),
    and a rotated ``ROSTER_API_TOKEN`` would 401 every six hours with no symptom
    anywhere. So every pull — scheduled, manual or uploaded — lands a row here,
    and ``/players/roster/`` reads the latest.

    Kept as a history rather than a single row so "it broke on Tuesday" is
    answerable. It is four rows a day against a table nothing joins to.

    See ``plans/PLAN_COCO_PROGRAM.md`` (W4, the pull half).
    """

    SCHEDULED = "scheduled"
    MANUAL = "manual"
    UPLOAD = "upload"
    SOURCES = [
        (SCHEDULED, "Scheduled"),
        (MANUAL, "Pulled by hand"),
        (UPLOAD, "Uploaded snapshot"),
    ]

    created_at = models.DateTimeField(auto_now_add=True)
    source = models.CharField(max_length=16, choices=SOURCES)
    ok = models.BooleanField(default=False)
    # Empty when ok. Carries the RosterFetchError/RosterParseError message,
    # which is already written to be read by an admin rather than a programmer.
    error = models.TextField(blank=True)
    # The document's own stamp — when the *central* database generated it, not
    # when we pulled it. A pull that keeps returning the same generated_at is a
    # central database that has stopped rebuilding.
    generated_at = models.CharField(max_length=40, blank=True)
    added = models.PositiveIntegerField(default=0)
    updated = models.PositiveIntegerField(default=0)
    unchanged = models.PositiveIntegerField(default=0)
    # Rows held back for a director to confirm, as PendingResolution.to_json()
    # dicts. Nothing was written for them. Entries are removed as each is
    # confirmed, so an empty list means there is nothing left to do.
    pending = models.JSONField(default=list, blank=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        outcome = "ok" if self.ok else "failed"
        return f"{self.get_source_display()} roster pull ({outcome})"

    @classmethod
    def latest(cls):
        """The most recent attempt, successful or not, or None."""
        return cls.objects.first()

    @classmethod
    def latest_successful(cls):
        """The most recent attempt that actually read a roster, or None.

        Held-back rows come from here rather than from :meth:`latest`, so a
        failed pull does not hide the resolutions the last good one found.
        """
        return cls.objects.filter(ok=True).first()

    @property
    def total(self):
        return self.added + self.updated + self.unchanged + len(self.pending)

    def summary(self):
        """One line for a log, a cron mail, or the page."""
        if not self.ok:
            return f"Roster pull failed: {self.error}"
        stamp = f" (generated {self.generated_at})" if self.generated_at else ""
        line = (
            f"Pulled {self.total} player(s){stamp}: {self.added} added, "
            f"{self.updated} updated, {self.unchanged} unchanged"
        )
        if self.pending:
            line += f", {len(self.pending)} awaiting confirmation"
        return line + "."


class WespaPlayer(models.Model):
    """One row of the WESPA rating list, mirrored locally.

    Baxter holds the whole list — some 9,200 players — rather than only applying
    it to players it already knows, because the players it does *not* know are
    the point. An overseas visitor at a CoCo event has no CoCo number and no CoCo
    rating; their WESPA rating is the only number anyone has for them, and until
    now a director typed it in at the registration desk from a website. Mirroring
    the list is what turns that into a search, and it is what lets the search
    work at a venue with no connection (plans/PLAN_WESPA.md decision 1).

    **Nothing here is a Baxter player.** A row becomes a :class:`Player` when a
    director enters one, and not before (decision 2). The link, once anyone has
    asserted it, lives on ``Player.wespa_id``.
    """

    # WESPA's own identifier, and the reason a link survives a name change on
    # either side. Not Baxter's key for anything else.
    wespa_id = models.IntegerField(unique=True)
    name = models.CharField(max_length=200)
    # Three-letter code as the source gives it, or blank: a fair number of rows
    # have none, and it is display data either way.
    country = models.CharField(max_length=8, blank=True)
    # NULL means the list carried no rating for them — the same convention as
    # ``Player.wespa_rating``, and distinct from a rating of 0. Every row has one
    # today; a row that stops having one stays searchable rather than vanishing,
    # since the name alone is still worth more than nothing at a registration
    # desk.
    rating = models.IntegerField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        indexes = [models.Index(fields=["name"])]

    def __str__(self):
        return f"{self.name} ({self.rating})"


class WespaSync(models.Model):
    """The outcome of one pull of the WESPA rating list.

    :class:`RosterSync`'s twin, for the same two reasons: a scheduled pull has
    nobody watching it, so a source that has gone away must leave a legible row
    rather than a silent nothing, and rows held back for a human to confirm must
    outlive the run that found them.

    The differences from ``RosterSync`` are the source's, not the design's:
    there is no token to rotate and no ``generated_at`` stamp in the document, so
    "when did this list last actually change" is answered by the counts.
    """

    SCHEDULED = "scheduled"
    MANUAL = "manual"
    UPLOAD = "upload"
    SOURCES = [
        (SCHEDULED, "Scheduled"),
        (MANUAL, "Pulled by hand"),
        (UPLOAD, "Uploaded file"),
    ]

    created_at = models.DateTimeField(auto_now_add=True)
    source = models.CharField(max_length=16, choices=SOURCES)
    ok = models.BooleanField(default=False)
    # Empty when ok. Carries the WespaFetchError/WespaParseError message, which
    # is written to be read by an admin rather than a programmer.
    error = models.TextField(blank=True)
    # The mirror: rows the pull added, changed, or found already correct.
    added = models.PositiveIntegerField(default=0)
    updated = models.PositiveIntegerField(default=0)
    unchanged = models.PositiveIntegerField(default=0)
    # The players: ratings written, and links newly asserted.
    rated = models.PositiveIntegerField(default=0)
    linked = models.PositiveIntegerField(default=0)
    # Links held back for a director to confirm, as PendingLink.to_json() dicts.
    # Nothing was written for these. Entries are removed as each is confirmed,
    # so an empty list means there is nothing left to do.
    pending = models.JSONField(default=list, blank=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        outcome = "ok" if self.ok else "failed"
        return f"{self.get_source_display()} WESPA pull ({outcome})"

    @classmethod
    def latest(cls):
        """The most recent attempt, successful or not, or None."""
        return cls.objects.first()

    @classmethod
    def latest_successful(cls):
        """The most recent attempt that actually read a list, or None.

        Held-back links come from here rather than from :meth:`latest`, so a
        failed pull does not hide what the last good one found.
        """
        return cls.objects.filter(ok=True).first()

    @property
    def total(self):
        return self.added + self.updated + self.unchanged

    def summary(self):
        """One line for a log, a cron mail, or the page."""
        if not self.ok:
            return f"WESPA pull failed: {self.error}"
        line = (
            f"Read {self.total} WESPA player(s): {self.added} added, "
            f"{self.updated} updated, {self.unchanged} unchanged; "
            f"{self.rated} local rating(s) written"
        )
        if self.linked:
            line += f", {self.linked} newly linked"
        if self.pending:
            line += f", {len(self.pending)} awaiting confirmation"
        return line + "."
