from django.urls import path

from .views import (
    AddFixedPairingView,
    BulkImportEntrantsView,
    CreatePlayerView,
    DivisionAllResultsView,
    DivisionCreateView,
    DivisionDeleteView,
    DivisionDetailView,
    DivisionRestoreView,
    DivisionScorecardsView,
    DivisionEditResultsView,
    DivisionEntrantsEditView,
    DivisionEntrantsView,
    DivisionBoardTableMapEditView,
    DivisionFixedPairingsEditView,
    DivisionFixedTablesEditView,
    DivisionPairingsView,
    DivisionSettingsEditView,
    DivisionStandingsView,
    PublishPairingsView,
    PublishedPairingsView,
    RemoveFixedPairingView,
    RemoveFixedPairingsView,
    ResultSlipCreateView,
    RoundPairingsTabView,
    SimulateMatchView,
    SimulateRoundView,
    TournamentCreateView,
    TournamentDeleteView,
    TournamentDetailView,
    TournamentListView,
    TournamentUpdateView,
)

urlpatterns = [
    path("", TournamentListView.as_view(), name="tournament_list"),
    path("<int:pk>/", TournamentDetailView.as_view(), name="tournament_detail"),
    path("create/", TournamentCreateView.as_view(), name="tournament_create"),
    path("<int:pk>/edit/", TournamentUpdateView.as_view(), name="tournament_edit"),
    path("<int:pk>/delete/", TournamentDeleteView.as_view(), name="tournament_delete"),
    path("division/<int:pk>/", DivisionDetailView.as_view(), name="division_detail"),
    path("division/<int:pk>/entrants/", DivisionEntrantsView.as_view(), name="division_entrants"),
    path("division/<int:pk>/results/", DivisionAllResultsView.as_view(), name="division_all_results"),
    path("division/<int:pk>/add-result/", ResultSlipCreateView.as_view(), name="resultslip_create"),
    path("division/<int:pk>/standings/", DivisionStandingsView.as_view(), name="division_standings"),
    path("division/<int:pk>/standings/<int:round>/", DivisionStandingsView.as_view(), name="division_standings_round"),
    path("division/<int:pk>/pairings/", DivisionPairingsView.as_view(), name="division_pairings"),
    path("division/<int:pk>/pairings/<int:round>/", RoundPairingsTabView.as_view(), name="round_pairings_tab"),
    path("division/<int:pk>/edit-entrants/", DivisionEntrantsEditView.as_view(), name="division_entrants_edit"),
    path("division/<int:pk>/settings/", DivisionSettingsEditView.as_view(), name="division_settings"),
    path("division/<int:pk>/edit-results/", DivisionEditResultsView.as_view(), name="division_edit_results"),
    path("division/<int:pk>/simulate-match/", SimulateMatchView.as_view(), name="simulate_match"),
    path("division/<int:pk>/simulate-round/", SimulateRoundView.as_view(), name="simulate_round"),
    path("division/<int:pk>/publish-pairings/", PublishPairingsView.as_view(), name="publish_pairings"),
    path("division/<int:pk>/add-fixed-pairing/", AddFixedPairingView.as_view(), name="add_fixed_pairing"),
    path("division/<int:pk>/remove-fixed-pairing/", RemoveFixedPairingView.as_view(), name="remove_fixed_pairing"),
    path("division/<int:pk>/remove-fixed-pairings/", RemoveFixedPairingsView.as_view(), name="remove_fixed_pairings"),
    path("division/<int:pk>/published-pairings/", PublishedPairingsView.as_view(), name="published_pairings"),
    path("division/<int:pk>/scorecards/", DivisionScorecardsView.as_view(), name="division_scorecards"),
    path("<int:tournament_pk>/division/create/", DivisionCreateView.as_view(), name="division_create"),
    path("division/<int:pk>/delete/", DivisionDeleteView.as_view(), name="division_delete"),
    path("division/<int:pk>/restore/", DivisionRestoreView.as_view(), name="division_restore"),
    path("division/<int:pk>/fixed-pairings/", DivisionFixedPairingsEditView.as_view(), name="division_fixed_pairings"),
    path("division/<int:pk>/fixed-tables/", DivisionFixedTablesEditView.as_view(), name="division_fixed_tables"),
    path("division/<int:pk>/board-tables/", DivisionBoardTableMapEditView.as_view(), name="division_board_tables"),
    path("division/<int:pk>/bulk-import/", BulkImportEntrantsView.as_view(), name="bulk_import_entrants"),
    path("create-player/", CreatePlayerView.as_view(), name="create_player"),
]
