//! Upstream's RNG, exactly: `golang.org/x/exp/rand`'s 128-bit PCG source and the
//! `Rand` methods COP uses.
//!
//! Exactness is the point. With the same seed and the same worker count, the
//! port's simulations are then bit-identical to liwords', so every stage of the
//! port can be checked against the oracle's log exactly rather than
//! statistically (`plans/PLAN_COP_GO_PORT.md`, decision 1). Test vectors below
//! were generated by running upstream's code.

const MULTIPLIER: u128 = 47026247687942121848144207491837523525;
const INCREMENT: u128 = 117397592171526113268558934119004209487;

#[derive(Debug, Clone)]
pub struct Rand {
    state: u128,
}

impl Rand {
    /// `rand.New(rand.NewSource(seed))`. PCGSource.Seed sets both halves of the
    /// state to the seed.
    pub fn new(seed: u64) -> Self {
        Rand { state: ((seed as u128) << 64) | seed as u128 }
    }

    /// PCGSource.Uint64: multiply, add, then an xor-rotate of the two halves.
    pub fn uint64(&mut self) -> u64 {
        self.state = self.state.wrapping_mul(MULTIPLIER).wrapping_add(INCREMENT);
        let high = (self.state >> 64) as u64;
        let low = self.state as u64;
        (high ^ low).rotate_right((high >> 58) as u32)
    }

    /// Rand.Uint64n: a mask for powers of two, else rejection above the largest
    /// multiple of `n`.
    pub fn uint64n(&mut self, n: u64) -> u64 {
        assert!(n > 0, "invalid argument to Uint64n");
        if n & (n - 1) == 0 {
            return self.uint64() & (n - 1);
        }
        let mut v = self.uint64();
        if v > u64::MAX - n {
            let ceiling = u64::MAX - u64::MAX % n;
            while v >= ceiling {
                v = self.uint64();
            }
        }
        v % n
    }

    /// Rand.Intn.
    pub fn intn(&mut self, n: usize) -> usize {
        self.uint64n(n as u64) as usize
    }

    /// Rand.Int63: the source's output with the top bit cleared.
    pub fn int63(&mut self) -> i64 {
        (self.uint64() & !(1u64 << 63)) as i64
    }

    /// Rand.Shuffle (Fisher–Yates from the top, `Int31n` below 2^31).
    pub fn shuffle<T>(&mut self, items: &mut [T]) {
        let mut i = items.len();
        while i > 1 {
            i -= 1;
            let j = self.uint64n(i as u64 + 1) as usize;
            items.swap(i, j);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // From upstream's own code (golang.org/x/exp/rand at the oracle's pin).

    #[test]
    fn uint64_matches_upstream() {
        let mut r = Rand::new(1);
        assert_eq!(
            [r.uint64(), r.uint64(), r.uint64()],
            [3812638179211989351, 9330348978533091121, 10626674221466475072]
        );
    }

    #[test]
    fn derived_methods_match_upstream() {
        let mut r = Rand::new(0xDEADBEEF);
        assert_eq!((0..5).map(|_| r.intn(10)).collect::<Vec<_>>(), vec![2, 9, 4, 0, 8]);
        assert_eq!((0..4).map(|_| r.intn(2)).collect::<Vec<_>>(), vec![1, 0, 0, 1]);
        assert_eq!((0..3).map(|_| r.intn(6771)).collect::<Vec<_>>(), vec![348, 4414, 422]);
        assert_eq!([r.int63(), r.int63()], [2833826541520642937, 6070180079028555375]);
        let mut s: Vec<usize> = (0..10).collect();
        r.shuffle(&mut s);
        assert_eq!(s, vec![2, 1, 4, 7, 0, 8, 5, 3, 9, 6]);
    }

    #[test]
    fn a_seed_past_i64_matches_upstream() {
        let mut r = Rand::new(18446744073709551000);
        assert_eq!(r.uint64(), 11067600767989213024);
        assert_eq!(r.intn(1000), 329);
    }
}
